version: '3.8'

services:
  # Django-Datenbank (PostgreSQL)
  database_django:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_django:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend (Django)
  backend:
    build:
      context: .
      dockerfile: ./Backend_django/Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      database_django:
        condition: service_healthy
    volumes:
      - ./Backend_django:/app
    command: ["sh", "-c", "/app/init.sh && python manage.py runserver 0.0.0.0:8000"]

  # Frontend (React mit Vite und NGINX)
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./Frontend/Dockerfile
  #   container_name: react_app
  #   ports:
  #     - "3000:3000"  # Vite Entwicklungsserver auf Port 3000
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://backend:8000
  #   volumes:
  #     - ./Frontend:/app
  #     - /app/node_modules


networks:
  app-network:
    driver: bridge

volumes:
  postgres_django: