version: '3.8'

services:

  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:5432"

  prisma-studio:
    image: node:lts
    working_dir: /app
    volumes:
      - ./Backend:/app
      - ./.env:/app/.env
    ports:
      - "5555:5555"
    command: >
      sh -c "if [ ! -d node_modules ]; then npm install; fi && npx prisma studio --port 5555"
    depends_on:
      - database

volumes:
  postgres_data:
