# Use an official Node.js runtime as a parent image
FROM node:20


# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Run the development server (vite)
CMD ["npm", "run", "dev"]
